repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10 # Replace with the latest stable Ruff release
    hooks:
      - id: ruff-check
        args: [--fix] # Optional: automatically fix linting issues
      - id: ruff-format
