#:kivy 1.10
<ZenButton@ButtonBehavior+Label>:
    canvas.before:
        # Outer rectangle
        Color:
            rgba: [0.2, 0.2, 1, 1.0]
        RoundedRectangle:
            pos: self.pos
            size: self.size
        # Inner
        Color:
            rgba: [0.5, 0.5, 0.1, 1] if root.state == "down" else [0.25, 0.25, 0.75, 1]
        RoundedRectangle:
            pos: self.x + 2, self.y + 2
            size: self.width - 4, self.height - 4