#:kivy 1.10
#: set gap 4

<ZenIcon>:
    canvas.before:
        Color:
            rgba: root.back_color
        Rectangle:
            pos: self.x - gap, self.y - gap
            size: self.width + 2 * gap, self.height + 1.25 * gap
        Color:
            rgba: [*root.back_color[:3], root.back_color[3] * 2]
        Line:
            rectangle: self.x, self.y, self.width, self.height

    size_hint: None, 1
    width: self.height
