"""
Houses the ZenRecycleView class
"""
from kivy.uix.floatlayout import FloatLayout
from kivy.uix.recycleview.views import RecycleDataViewBehavior
from kivy.properties import BooleanProperty, ListProperty, ObjectProperty
from kivy.uix.label import Label
from kivy.uix.behaviors import FocusBehavior
from kivy.uix.recycleboxlayout import RecycleBoxLayout
from kivy.uix.recycleview.layout import LayoutSelectionBehavior
from ui.kvloader import KVLoader
from kivy.clock import Clock
from kivy.animation import Animation
from kivy.properties import StringProperty, BooleanProperty


class ZenRecycleView(FloatLayout):
    """
    Provides a shared component for Playlist and Library recycleviews.
    """
    handler = ObjectProperty()
    """ Object that should handle the "on_selected" method. """

    data = ObjectProperty([])
    """ The data synchronized with the recycleview """

    search_text = StringProperty("")
    """
    Text entered by the user to move to the first artist staring with the
    text.
    """
    note_text = StringProperty("Loading library. Please wait..")
    """
    The text, obtained from the keyboard, for searched for items in the list
    of atists.
    """

    show_note = BooleanProperty(True)
    """
    Boolean property dictating whether or not the notification label should
    be dispalyed.
    """

    def __init__(self, **kwargs):
        KVLoader.load("ui/widgets/zenrecycleview.kv")
        super().__init__(**kwargs)

    def on_data(self, _widget, _value):
        """ Remove the loading warning once data is loaded. """
        self.note_text = ""

    def find_item(self, text):
        """ Jump to the first item that has a text match with *text* """
        length = len(self.data)
        text = text.lower()
        for i, data in enumerate(self.data):
            if data["text"].lower().find(text) > -1:
                self.ids.rv.scroll_y = 1.0 - 1.005 * float(i) / float(length)
                return

    def on_show_note(self, widget, value):
        """ Either hide of show the note label """
        end_value = 1 if value else 0
        Animation(opacity=end_value, duration=2).start(self.ids.note_label)

    def on_note_text(self, widget, text):
        """ Handle the change of note text """
        self.show_note = bool(text)

    def on_search_text(self, widget, text):
        """ Handle the display and mechanics of searching for matches """
        if text:
            self.note_text = f"Searching for: {text}"
            self.find_item(text)
        else:
            self.note_text = ""

    def on_key_down(self, keycode, text, modifiers):
        """ Respond the pressing of a key """
        # print(f"Got keydown text: {text}, keybode={keycode}")
        if text is not None:
            self.search_text += text
        elif keycode[0] == 8 and self.search_text:  # delete
            self.search_text = self.search_text[:-1]
        elif keycode[0] == 27:  # escape
            self.search_text = ""


class SelectableLabel(RecycleDataViewBehavior, Label):
    """
    Add selection support to the Label
    """
    index = None
    """ The index of the active label in the RecycleViews' data property """

    back_color = ListProperty([0, 0, 0, 1])

    selected = BooleanProperty(False)
    """ Indicates whether this item has been selected or not. """

    handler = None
    """
    Reference to the obejct that should handle the events generated by the
    RecyleView, namely:

        * item_selected(item, True/False)
        * item_touched(item)
        * item_draw(item)
    """

    def item_draw(self):
        """ Handle the setting of the label back_color, so we call pull this
        logic out of the recycleview rabbit hole.
        """
        if self.selected:
            self.back_color = [.5, .5, 1.0, .3]
        else:
            self.back_color = [0, 0, 0, 1]

    def refresh_view_attrs(self, rv, index, data):
        """ Catch and handle the view changes """
        self.index = index
        return super().refresh_view_attrs(rv, index, data)

    def apply_selection(self, rv, index, is_selected):
        """ Respond to the selection of items in the view. """
        self.selected = is_selected
        handler = self.handler = rv.handler
        if hasattr(handler, "item_selected"):
            handler.item_selected(self, is_selected)
        if hasattr(handler, "item_draw"):
            if handler.item_draw(self):
                return
        self.item_draw()

    def on_touch_down(self, touch):
        """ Add selection on touch down """
        if super().on_touch_down(touch):
            return True
        if self.collide_point(*touch.pos):
            if self.handler and hasattr(self.handler, "item_touched"):
                Clock.schedule_once(lambda dt: self.handler.item_touched(self))
            return self.parent.select_with_touch(self.index, touch)


class SelectableRecycleBoxLayout(FocusBehavior, LayoutSelectionBehavior,
                                 RecycleBoxLayout):
    """ Adds selection and focus behaviour to the view. """
